#### Top-level fields ####
spec-version:                       0.31.0
name:                               hlint-minicute-utilities
version:                            0.1.0.0
synopsis:                           Experimental package for a language implemented by Haskell
description: >
  This package is only for experiment to implement CUTE Lang.
  Do not use this any other purpose. This package would
  introduce breaking changes without any notifications.
category:                           Language
## Practically deprecated
# stability:
## Following two are inferred from "github" field.
# homepage:
# bug-reports:
author:                             Junyoung Clare Jang
maintainer:                         jjc9310@gmail.com
copyright:                          2018-present Junyoung Clare Jang
## Inferred from license-file
license:                            BSD-3-Clause
license-file:                       LICENSE
# tested-with:
# build-type:
# extra-source-files:
extra-doc-files:                    README.md
# data-files:
# data-dir:
github:                             CUTE-Lang/miniCUTE/utilities/hlint
## Following is ignored when "github" field exists
# git:
# custom-setup:

#### Sections ####
# flags:

library:
  ### Library fields ###
  # exposed:
  # exposed-modules:
  # generated-exposed-modules:
  # other-modules:
  # generated-other-modules:
  # reexported-modules:
  # signatures:

  ### Common fields ###
  source-dirs:
    - lib
  ghc-options:
    - -Wall
  dependencies:
    - directory >= 1.3 && < 2
    - filepath >= 1.4 && < 2
    - hlint >= 2.1 && < 3

# internal-libraries:

executables:
  hlint-run:
    ### Executable fields ###
    main:                           Main.hs
    # other-modules:
    # generated-other-modules:

    ### Common fields ###
    source-dirs:
      - hlint-run
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hlint-minicute-utilities == 0.1.0.0

# executable:

tests:
  hlint:
    ### Test fields ###
    main:                           Main.hs
    # other-modules:
    # generated-other-modules:

    ### Common fields ###
    source-dirs:
      - hlint
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hlint-minicute-utilities
    build-tools:
      - hlint-minicute-utilities:hlint-run

# benchmarks:

# defaults:
  # github:
  # ref:
  # path:
  # local:

#### Common fields ####
# buildable:
# source-dirs:
# default-extensions:
# other-extensions:
# ghc-options:
# ghc-prof-options:
# ghcjs-options:
# cpp-options:
# cc-options:
# c-sources:
# cxx-options:
# cxx-sources:
# js-sources:
# extra-lib-dirs:
# extra-libraries:
# include-dirs:
# install-includes:
# frameworks:
# extra-frameworks-dirs:
# ld-options:
dependencies:
  - base >= 4.12 && < 5
# pkg-config-dependencies:
# build-tools:
# system-build-tools:
# when:
