{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TemplateHaskellQuotes #-}
-- |
-- Tuple functions used in miniCUTE compiler
module Data.Tuple.Minicute
  ( module Data.Tuple

  , TupleZipper1( .. )
  , TupleZipper2( .. )
  , TupleZipper3( .. )
  , TupleZipper4( .. )
  , TupleZipper5( .. )
  , TupleZipper6( .. )
  , TupleZipper7( .. )
  , TupleZipper8( .. )
  , TupleZipper9( .. )
  ) where

import Data.Tuple
import Data.Tuple.Internal.Minicute.TH

-- * TupleConverters

-- $templateHaskell
-- Following classes/instances are automatically generated by TemplateHaskell.

makeTupleZippers 9
